### ISSUE TITLE
Yarn is already included in docker-node

### ISSUE THREAD

**Issue by flintinatux** [articulate/docker-articulate-node#15]
We currently install a fixed version of `yarn`, but it appears that the version we install is not even being used.  I spotted this in my logs today:
```
Step 5/9 : RUN yarn run build
 ---> Running in 223cc01687fe
yarn run v0.22.0
```
We currently install 0.21.3.  It appears that we should just rip all that out, since `yarn` is already included in the upstream image.  See also https://github.com/nodejs/docker-node/pull/376.

cc @tecnobrat or @plukevdh or whomever else might be interested

**Comment by rpearce** [comment]
Should this issue still be open?
